apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipeshub-ai.fullname" . }}-kafka
  labels:
    {{- include "pipeshub-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  replicas: {{ .Values.kafka.replicaCount }}
  selector:
    matchLabels:
      {{- include "pipeshub-ai.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: kafka
  template:
    metadata:
      labels:
        {{- include "pipeshub-ai.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: kafka
    spec:
      securityContext:
        {{- toYaml .Values.kafka.podSecurityContext | nindent 8 }}
      containers:
        - name: kafka
          image: "{{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag }}"
          imagePullPolicy: {{ .Values.kafka.image.pullPolicy }}
          ports:
            - containerPort: 9092
              name: kafka
          env:
            - name: KAFKA_BROKER_ID
              value: {{ .Values.kafka.config.brokerId | quote }}
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "{{ include "pipeshub-ai.fullname" . }}-zookeeper:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "ACCESS:PLAINTEXT"
            - name: KAFKA_LISTENERS
              value: "ACCESS://0.0.0.0:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "ACCESS://{{ include "pipeshub-ai.fullname" . }}-kafka:9092"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "ACCESS"
            - name: KAFKA_CREATE_TOPICS
              value: "record-events:1:1,entity-events:1:1,sync-events:1:1"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: {{ .Values.kafka.config.offsetsTopicReplicationFactor | quote }}
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: {{ .Values.kafka.config.transactionStateLogMinIsr | quote }}
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: {{ .Values.kafka.config.transactionStateLogReplicationFactor | quote }}
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: {{ .Values.kafka.config.groupInitialRebalanceDelayMs | quote }}
            - name: KAFKA_LOG_RETENTION_HOURS
              value: {{ .Values.kafka.config.logRetentionHours | quote }}
            - name: KAFKA_NUM_NETWORK_THREADS
              value: {{ .Values.kafka.config.numNetworkThreads | quote }}
            - name: KAFKA_NUM_IO_THREADS
              value: {{ .Values.kafka.config.numIoThreads | quote }}
          resources:
            {{- toYaml .Values.kafka.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.kafka.securityContext | nindent 12 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "pipeshub-ai.fullname" . }}-kafka
  labels:
    {{- include "pipeshub-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
spec:
  type: "ClusterIP"
  ports:
    - port: 9092
      targetPort: kafka
      protocol: TCP
      name: kafka
  selector:
    {{- include "pipeshub-ai.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka
